<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RollForward>Major</RollForward>
    <OutputType>WinExe</OutputType>
    <PublishReadyToRun>false</PublishReadyToRun>
    <TieredCompilation>false</TieredCompilation>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>

  <ItemGroup>
    <MonoGameContentReference Include="Content\Content.mgcb" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MonoGame.Framework.DesktopGL" Version="3.8.1.303" />
    <PackageReference Include="MonoGame.Content.Builder" Version="3.7.0.9" />
    <PackageReference Include="MonoGame.Extended" Version="3.8.0" />
    <PackageReference Include="DefaultEcs" Version="0.18.0-beta01" />
    <PackageReference Include="Myra" Version="1.3.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="RoyT.AStar" Version="1.0.0" />
  </ItemGroup>

</Project>

